### ISSUE TITLE
ValueError: spacy.strings.StringStore size changed, may indicate binary incompatibility. Expected 112 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by dzimmerman-nci** [dmmiller612/bert-extractive-summarizer#20] opened 2019-10-29 19:29 UTC
I am trying to run the example code and keep getting this error.

**Comment by dzimmerman-nci** [comment] 2019-10-29 20:34
I have confirmed that all of my requirements are the same version as the project's

**Comment by dzimmerman-nci** [comment] 2019-10-30 13:53
it looks like this might have been a python 3.7 problem. python 3.6 is working for me.

**Comment by dmmiller612** [comment] 2019-10-31 11:29
Interesting. I'll take a look this weekend to get a bug fix/new docker image.

**Comment by Sid8519** [comment] 2019-11-02 05:37
I tried both examples and am getting this type of error ending with segmentation 11, I used Python 3.7, I will try with Python 3.6, interesting project!
 /opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.morphology.Morphology size changed, may indicate binary incompatibility. Expected 104 from C header, got 112 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.vocab.Vocab size changed, may indicate binary incompatibility. Expected 96 from C header, got 104 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)
Segmentation fault: 11

**Comment by Sid8519** [comment] 2019-11-04 04:11
So when I set up a conda environment for python 3.6 the thing works perfectly

**Comment by dmmiller612** [comment] 2019-11-04 19:29
I am guessing the 3.7 issue is related to the spacy lock we are currently in, due to limited support from neuralcoref. Probably worth making neuralcoref optional to get around issues like this.

**Comment by TheEdoardo93** [comment] 2019-11-12 10:39
Taken from [here](https://github.com/huggingface/neuralcoref):
_If you have an error mentioning_ `spacy.strings.StringStore size changed`, _may indicate binary incompatibility when loading NeuralCoref with import neuralcoref, it means you'll have to install NeuralCoref from the distribution's sources instead of the wheels to get NeuralCoref to build against the most recent version of SpaCy for your system._

_In this case, simply re-install neuralcoref as follows:_

```
pip uninstall neuralcoref
pip install neuralcoref --no-binary neuralcoref
```

**Comment by AlaFalaki** [comment] 2019-11-21 17:34
@dmmiller612 
I am using Python 3.6.3 and have the "Segmentation fault" error. (also sure about the requirements version)
The library works well on google Colab but not on the servers I am working on.

**Comment by dmmiller612** [comment] 2019-11-23 15:28
Thanks @TheEdoardo93, I'll add those instructions to the README. @AlaFalaki, per the neuralcoref instructions, you will need to follow TheEdoarado93 instructions.

**Comment by AlaFalaki** [comment] 2019-11-27 17:06
@dmmiller612 I tried @TheEdoardo93's instruction before asking. It did not help.
I made a new virtual environment and reinstalled the module (pip install bert-extractive-summarizer), now everything works fine. Don't know why exactly.

**Comment by dmmiller612** [comment] 2019-11-28 18:49
Yeah, that is strange. It is most likely a neuralcoref issue. Neuralcoref and spacy have had some issues with some versions, but the current locked versions in the readme should work. I'll see if I can reproduce.

**Comment by dmmiller612** [comment] 2020-04-14 13:22
This issue was due to the coreference package. This has been addressed in recent versions, allowing coreference to be an add on rather than required. Closing for now.

**Closed by dmmiller612** 2020-04-14 13:22 UTC
